#!/bin/bash

_uid=$(id -u)

if (( _uid != 0 )); then
	exec sudo "$0" "$@"
	exit $?
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -eu

cd "$DIR"

aptitude install -y \
  acpi acpi-call-dkms acpid acpi-support-base cpufrequtils intel-microcode \
  iucode-tool laptop-detect libdrm-intel1 libgl1-mesa-dri rsync smartmontools \
  smartmontools tlp xbacklight xserver-xorg-video-intel

find etc/ -type f ! -iname "*.sw?" \
	-exec install -g root -o root -m 0755 -C -D -v {} /{} \;

if ! type -P xflux &>/dev/null; then
	tmpdir="$(mktemp -d)"
	( cd "$tmpdir"
		wget -c "https://justgetflux.com/linux/xflux64.tgz"
		tar xf xflux64.tgz
		install -g root -o root -m 0755 -C -D -v xflux /usr/local/bin/xflux
	)
	rm -fr "$tmpdir"
fi

service acpid restart
